name: Debug Build

on: push

jobs:
  build-debug:
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    steps:
      - name: Checkout and initialise
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract Dalamud version
        id: dalamud-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "./LMeter/LMeter.csproj"
          xpath: "//DalamudVersion"

      - name: CSProj Cache
        id: cache-csproj
        uses: actions/cache@v2
        with:
          path: |
            ./dalamud
            ~/.nuget/packages
          key: ${{ runner.os }}-csproj-v3-${{ hashFiles('**/*.csproj') }}

      - name: Setup Dalamud
        if: "!contains(github.event.head_commit.message, '[stg]')"
        shell: pwsh
        run: |
          mkdir ./dalamud
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile ./dalamud/latest.zip
          Expand-Archive -Path ./dalamud/latest.zip ./dalamud

      - name: Setup stg Dalamud
        if: "contains(github.event.head_commit.message, '[stg]')"
        shell: pwsh
        run: |
          mkdir ./dalamud
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile ./dalamud/latest.zip
          Expand-Archive -Path ./dalamud/latest.zip ./dalamud

      - name: Restore project dependencies
        run: dotnet restore --verbosity normal

      - name: Build Debug
        run: dotnet build --no-restore --verbosity normal --configuration Debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LMeter-debug-${{ github.sha }}
          path: |
            LMeter/bin/x64/Debug
            !LMeter/bin/x64/Debug/LMeter
